version: '3'
services:
  cookiecloud:
    image: easychen/cookiecloud:latest
    container_name: cookiecloud-app
    restart: unless-stopped
    volumes:
      - ./data:/data/api/data
    ports:
      - "8088:8088"