version: "3"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: always 
    environment:
      - SIGNUPS_ALLOWED=true
      - INVITATIONS_ALLOWED=true
      - WEBSOCKET_ENABLED=true
      - SHOW_PASSWORD_HINT=hint
    volumes:
      - ./bw-data:/data/
    ports:
      - 9007:80
