version: "3"
services: 
  db:
    image: mysql:latest
    restart: unless-stopped
    command: 
      - "--lower_case_table_names=1"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
      - "--explicit_defaults_for_timestamp=true"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: mysql123456
    ports:
      - 3306:3306
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
