version: "3"
services: 
  db:
    image: mysql
    container_name: mysql
    restart: always
    command: 
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: kserver
    ports:
      - 3306:3306
    volumes: 
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
