version: "3"
services: 
  app:
    image: mebtte/cicada
    container_name: cicada
    restart: always
    ports:
      - 9012:80
    volumes:
      - ./data:/data
      - ./cicada-config.json:/config.json