version: "3"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett
    ports:
      - 9117:9117
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    environment:
      - UMASK=022 # 掩码权限，默认000，可以考虑设置为022
    restart: always 