version: "3.0"

services:
  talebook:
    restart: always
    image: talebook/talebook
    volumes:
      - ./data:/data
    ports:
      - "9002:80"
      - "9003:443"s
    depends_on:
      - douban-rs-api

  # optional, for meta plugins
  # please set "http://douban-rs-api" in settings
  douban-rs-api:
    restart: always
    image: ghcr.io/cxfksword/douban-api-rs
