version: "3"

services:
  qbittorrent:
    image: nevinee/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    tty: true
    ports:
      - "15010:15010"     # 冒号左右一致，必须同WEBUI_PORT
      - "34567:34567"      # 冒号左右一致，必须同BT_PORT
      - "34567:34567/udp"  # 冒号左右一致，必须同BT_PORT
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - QB_USERNAME=qbittorrent
      - QB_PASSWORD=qbittorrent
      - WEBUI_PORT=15010   # WEBUI控制端口，可自定义
      - BT_PORT=34567     # BT监听端口，可自定义
      - TZ=Asia/Shanghai  # 时区
    volumes:
      - ./data:/data
