version: "3"
services:
  wewe-rss-sqlite:
    container_name: wewe-rss
    ports:
        - 15009:4000
    environment:
        - DATABASE_TYPE=sqlite
        - AUTH_CODE=authcode
    volumes:
        - ./data:/app/data
    image: cooderl/wewe-rss-sqlite:latest