version: '3'

services:
  rsshub:
    image: diygod/rsshub:chromium-bundled
    restart: unless-stopped
    ports:
        - '1200:1200'
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis:6379/'
      # PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'  # marked
    depends_on:
      - redis
      # - browserless  # marked

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis/data:/data