version: "3"
services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    ports:
      - "5212:5212"
    volumes:
      - ./data:/data
      - ./downloads:/downloads
      - ./cloudreve/config:/cloudreve/config
      - ./cloudreve/uploads:/cloudreve/uploads
      - ./cloudreve/avatar:/cloudreve/avatar
    depends_on:
      - aria2
  aria2:
    container_name: aria2
    image: p3terx/aria2-pro # third party image, please keep notice what you are doing
    restart: unless-stopped
    environment:
      - RPC_SECRET=123456
      - RPC_PORT=6800
      - LISTEN_PORT=6888
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    volumes:
      - ./aria2/config:/config
      - ./downloads:/downloads
      - ./data:/data
